listen:
- 127.0.0.1:8080
- "[::1]:8080"
compression_level: 3
root: ../../static-files-module/testdata/root
canonicalize_uri: true
log_file: "access.log"
index_file:
- index.html
precompressed:
- gz
- br
rewrite_rules:
- from: /old.txt
  query_regex: "!noredirect"
  to: /file.txt
  type: permanent
- from: /view.php
  query_regex: "^file=large\\.txt$"
  to: /large.txt
- from: /images/*
  from_regex: "\\.jpg$"
  to: https://example.com${tail}
  type: redirect
custom_headers:
- headers:
    Cache-Control: "max-age=604800"
  include: [/*]
  exclude: [/large.txt]
