listen:
- 127.0.0.1:8080
- "[::1]:8080"
compression_level: 3
root: ../../static-files-module/testdata/root
canonicalize_url: true
index_file:
- index.html
precompressed:
- gz
- br
custom_headers:
- headers:
    Cache-Control: "max-age=604800"
  include: [/*]
  exclude: [/large.txt]
