listen:
- 127.0.0.1:8080
- "[::1]:8080"
- 127.0.0.1:8081
- "[::1]:8081"
vhosts:
  localhost:8080:
    aliases:
      - 127.0.0.1:8080
      - "[::1]:8080"
    default: true
    root: ../../static-files-module/testdata/root
    canonicalize_url: true
    index_file:
    - index.html
    compression_level: 3
    precompressed:
    - gz
    - br
    subdirs:
      /uncompressed:
        strip_prefix: true
        root: ../../static-files-module/testdata/root
        redirect_prefix: /uncompressed
      /reindexed:
        strip_prefix: true
        index_file:
        - file.txt
        canonicalize_url: false
        compression_level: 3
        precompressed:
        - gz
        - br
  localhost:8081:
    aliases:
      - 127.0.0.1:8081
      - "[::1]:8081"
    upstream: https://example.com/
