listen:
- 127.0.0.1:8080
- "[::1]:8080"
- 127.0.0.1:8081
- "[::1]:8081"
vhosts:
  localhost:8080:
    aliases:
      - 127.0.0.1:8080
      - "[::1]:8080"
    default: true
    log_file: localhost.access.log
    log_format: [remote_addr, -, -, time_local, request, status, bytes_sent, http_referer, http_user_agent, processing_time]
    root: ../../static-files-module/testdata/root
    canonicalize_uri: true
    index_file:
    - index.html
    compression_level: 3
    precompressed:
    - gz
    - br
    rewrite_rules:
    - from: /old.txt
      query_regex: "!noredirect"
      to: /file.txt
      type: permanent
    - from: /view.php
      query_regex: "^file=large\\.txt$"
      to: /large.txt
    - from: /images/*
      from_regex: "\\.jpg$"
      to: https://example.com${tail}
      type: redirect
    subdirs:
      /uncompressed:
        strip_prefix: true
        log_file: localhost.access.log
        root: ../../static-files-module/testdata/root
        redirect_prefix: /uncompressed
      /reindexed:
        strip_prefix: true
        log_file: localhost.access.log
        root: ../../static-files-module/testdata/root
        index_file:
        - file.txt
        canonicalize_uri: false
        compression_level: 3
        precompressed:
        - gz
        - br
  localhost:8081:
    aliases:
      - 127.0.0.1:8081
      - "[::1]:8081"
    log_file: upstream.access.log
    upstream: https://example.com/
custom_headers:
- headers:
    Cache-Control: "max-age=604800"
  include: [localhost:8080]
  exclude: [localhost:8080/large.txt]
- headers:
    Cache-Control: "max-age=3600"
  include: [localhost:8080/uncompressed/*]
  exclude: [localhost:8080/uncompressed/large.txt]
- headers:
    Cache-Control: "no-cache"
    X-From: "https://example.com/"
  include: [localhost:8081, example.com]
